repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pycqa/flake8
  rev: '7.1.1'
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-coding
    - flake8-import-order
    - flake8-polyfill
    - flake8-quotes
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
  hooks:
  - id: black
- repo: https://github.com/rtts/djhtml
  rev: 3.0.7
  hooks:
  - id: djhtml
    files: .*/templates/.*\.html$
